import = ['./gruvbox.toml']

live_config_reload = true

[window]
# padding.x = 0
# padding.y = 10
decorations = "buttonless"
opacity = 0.8
blur = true
startup_mode = "Maximized"

[env]
TERM = "alacritty"

[font]
normal.family = "Iosevka Nerd Font Mono"
size = 12

[font.offset]
y = 1

[cursor]
style.blinking = 'Always'

# [[hints.enabled]]
# command = "xdg-open"
# hyperlinks = true
